version: "2"

services:
  consul:
    image: consul:latest
    ports:
      - "8500:8500"

  geolocation-1:
    image: vikrammurugesan/geolocation:latest
    ports:
      - "8080"
    environment:
      GEOLOCATION_SERVICE_PORT: "8080"
      
  geolocation-2:
    image: vikrammurugesan/geolocation:latest
    ports:
      - "8081"
    environment:
      GEOLOCATION_SERVICE_PORT: "8081"
      
  geolocation-consul-lb:
    image: vikrammurugesan/geolocation-consul-lb:latest
    ports:
      - "8899:8899"
  
      